"""Unified Inference Pipeline for EVIDENCE-Net (Phase 11).

Provides sample-to-artifact unified inference connecting the frozen Phase 4
Base Reconstruction and Bounded Detail Proposal models. Operates deterministically,
computes tensor metadata, calculates SHA256 hashes, handles optional diagnostic
layers with strict backward-compatibility fallbacks ("not-defined"), and writes
governed run bundles.
"""

from __future__ import annotations

import hashlib
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import torch

from evidence_net.evaluation.metrics import all_metrics
from evidence_net.inference.provenance import (
    ProvenanceRecord,
    build_provenance_record,
)
from evidence_net.models.base import BaseReconstruction
from evidence_net.models.proposal import DetailProposer
from evidence_net.reporting.run_bundle import (
    create_run_bundle,
    new_run_id,
    write_json,
)

FROZEN_TENSOR_KEYS = (
    "input.npy",
    "base.npy",
    "proposal.npy",
    "candidate.npy",
    "final.npy",
)

OPTIONAL_TENSOR_KEYS = (
    "proposal_benefit.npy",
    "measurement_consistency.npy",
    "model_stability.npy",
    "distribution_familiarity.npy",
    "decision_map.npy",
    "unresolved.npy",
)


@dataclass(frozen=True)
class TensorMetadata:
    """Metadata describing a saved tensor artifact."""

    dtype: str
    shape: list[int]
    range: list[float]
    hash: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "dtype": self.dtype,
            "shape": self.shape,
            "range": self.range,
            "hash": self.hash,
        }


def compute_tensor_metadata(arr: np.ndarray) -> TensorMetadata:
    """Compute tensor contract metadata (dtype, shape, range, sha256 hash)."""
    raw_bytes = arr.tobytes()
    digest = hashlib.sha256(raw_bytes).hexdigest()
    min_val = float(np.min(arr)) if arr.size > 0 else 0.0
    max_val = float(np.max(arr)) if arr.size > 0 else 0.0
    return TensorMetadata(
        dtype=str(arr.dtype),
        shape=list(arr.shape),
        range=[min_val, max_val],
        hash=f"sha256:{digest}",
    )


@dataclass
class UnifiedInferenceResult:
    """Outputs generated by one sample inference pass."""

    run_id: str
    run_dir: Path
    input_tensor: np.ndarray
    base_tensor: np.ndarray
    proposal_tensor: np.ndarray
    candidate_tensor: np.ndarray
    final_tensor: np.ndarray
    target_tensor: np.ndarray | None = None
    optional_tensors: dict[str, np.ndarray] = field(default_factory=dict)
    metrics: dict[str, Any] = field(default_factory=dict)
    provenance: ProvenanceRecord = field(default_factory=build_provenance_record)
    artifact_metadata: dict[str, dict[str, Any]] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "run_dir": str(self.run_dir),
            "metrics": self.metrics,
            "provenance": self.provenance.as_dict(),
            "artifact_metadata": self.artifact_metadata,
        }


class UnifiedInferencePipeline:
    """Unified inference driver connecting Base Reconstruction and Bounded Detail Proposal."""

    def __init__(
        self,
        base_model: BaseReconstruction | None = None,
        proposal_model: DetailProposer | None = None,
        device: str | torch.device = "cpu",
        provenance: ProvenanceRecord | None = None,
    ) -> None:
        self.device = torch.device(device)
        self.base_model = base_model.to(self.device).eval() if base_model is not None else None
        self.proposal_model = (
            proposal_model.to(self.device).eval() if proposal_model is not None else None
        )
        self.provenance = provenance or build_provenance_record()

    @classmethod
    def from_checkpoints(
        cls,
        base_checkpoint_path: Path | str | None = None,
        proposal_checkpoint_path: Path | str | None = None,
        device: str | torch.device = "cpu",
        provenance: ProvenanceRecord | None = None,
    ) -> UnifiedInferencePipeline:
        """Instantiate pipeline from checkpoint files if provided."""
        dev = torch.device(device)
        base_model: BaseReconstruction | None = None
        proposal_model: DetailProposer | None = None

        if base_checkpoint_path and Path(base_checkpoint_path).is_file():
            ckpt = torch.load(base_checkpoint_path, map_location=dev, weights_only=False)
            state_dict = ckpt.get("model_state_dict", ckpt)
            base_model = BaseReconstruction()
            base_model.load_state_dict(state_dict)

        if proposal_checkpoint_path and Path(proposal_checkpoint_path).is_file():
            ckpt = torch.load(proposal_checkpoint_path, map_location=dev, weights_only=False)
            state_dict = ckpt.get("model_state_dict", ckpt)
            proposal_model = DetailProposer()
            proposal_model.load_state_dict(state_dict)

        return cls(
            base_model=base_model,
            proposal_model=proposal_model,
            device=dev,
            provenance=provenance,
        )

    def run_sample(
        self,
        input_tensor: np.ndarray,
        target_tensor: np.ndarray | None = None,
        *,
        runs_dir: Path | str = Path("runs"),
        run_id: str | None = None,
        optional_tensors: Mapping[str, np.ndarray] | None = None,
        decision_mask: np.ndarray | None = None,
        optional_tensors_fn: Callable[[dict[str, np.ndarray]], dict[str, np.ndarray]] | None = None,
    ) -> UnifiedInferenceResult:
        """Run single-sample inference, save arrays, compute contract metadata, write run bundle."""
        rid = run_id or new_run_id("eval")
        rdir = Path(runs_dir)

        arr_input = np.clip(np.asarray(input_tensor, dtype=np.float32), 0.0, 1.0)
        if arr_input.ndim == 2:
            arr_input = arr_input[np.newaxis, ...]

        # Base inference
        if self.base_model is not None:
            t_in = torch.from_numpy(arr_input).unsqueeze(0).to(self.device)
            with torch.no_grad():
                t_base = self.base_model(t_in).squeeze(0).cpu().numpy()
            arr_base = np.clip(t_base, 0.0, 1.0)
        else:
            arr_base = arr_input.copy()

        # Proposal inference
        if self.proposal_model is not None:
            t_in = torch.from_numpy(arr_input).unsqueeze(0).to(self.device)
            t_b = torch.from_numpy(arr_base).unsqueeze(0).to(self.device)
            with torch.no_grad():
                t_prop = self.proposal_model(t_in, t_b).squeeze(0).cpu().numpy()
            arr_prop = np.asarray(t_prop, dtype=np.float32)
        else:
            arr_prop = np.zeros_like(arr_base, dtype=np.float32)

        # Ungated candidate
        arr_cand = np.clip(arr_base + arr_prop, 0.0, 1.0)

        # Final gated output
        if decision_mask is not None:
            arr_mask = np.asarray(decision_mask, dtype=np.float32)
            arr_final = np.clip(arr_base + arr_mask * arr_prop, 0.0, 1.0)
        else:
            arr_final = arr_cand.copy()

        # Metrics if target is provided
        computed_metrics: dict[str, Any] = {}
        if target_tensor is not None:
            arr_target = np.clip(np.asarray(target_tensor, dtype=np.float32), 0.0, 1.0)
            if arr_target.ndim == 2:
                arr_target = arr_target[np.newaxis, ...]

            if arr_target.shape != arr_base.shape:
                t_tgt = torch.from_numpy(arr_target).unsqueeze(0)
                t_tgt_up = torch.nn.functional.interpolate(
                    t_tgt, size=arr_base.shape[1:], mode="bilinear", align_corners=False
                )
                arr_target = t_tgt_up.squeeze(0).numpy()

            tgt_2d = np.squeeze(arr_target)
            base_2d = np.squeeze(arr_base)
            cand_2d = np.squeeze(arr_cand)
            final_2d = np.squeeze(arr_final)

            computed_metrics = {
                "base": all_metrics(tgt_2d, base_2d),
                "candidate": all_metrics(tgt_2d, cand_2d),
                "final": all_metrics(tgt_2d, final_2d),
            }

        # Create run bundle
        bundle_dir = create_run_bundle(
            rdir,
            rid,
            config={
                "pipeline": "UnifiedInferencePipeline",
                "device": str(self.device),
                "has_base_model": self.base_model is not None,
                "has_proposal_model": self.proposal_model is not None,
            },
            manifest={
                "schema": "artifacts-v1",
                "run_id": rid,
                "dataset_manifest_hash": self.provenance.dataset_manifest_hash,
            },
            metrics=computed_metrics,
            summary=f"Unified inference run {rid}",
            reference="unified-inference-pipeline",
        )

        artifacts_dir = bundle_dir / "artifacts"
        artifacts_dir.mkdir(parents=True, exist_ok=True)

        # Save frozen tensors
        tensor_dict: dict[str, np.ndarray] = {
            "input.npy": arr_input,
            "base.npy": arr_base,
            "proposal.npy": arr_prop,
            "candidate.npy": arr_cand,
            "final.npy": arr_final,
        }

        artifact_meta: dict[str, dict[str, Any]] = {}
        for name, arr in tensor_dict.items():
            path = artifacts_dir / name
            np.save(path, arr)
            meta = compute_tensor_metadata(arr)
            artifact_meta[name] = meta.as_dict()

        # Save optional tensors or mark "not-defined"
        opts = dict(optional_tensors or {})
        if optional_tensors_fn is not None:
            # Run-level diagnostics computed from this sample's own tensors
            # (e.g. benefit ranking, decision map, unresolved mask).
            opts.update(optional_tensors_fn(tensor_dict))
        if decision_mask is not None and "decision_map.npy" not in opts:
            opts["decision_map.npy"] = decision_mask

        optional_meta_present: dict[str, dict[str, Any]] = {}
        optional_meta_absent: dict[str, str] = {}

        for key in OPTIONAL_TENSOR_KEYS:
            if key in opts and opts[key] is not None:
                arr = np.asarray(opts[key])
                path = artifacts_dir / key
                np.save(path, arr)
                meta = compute_tensor_metadata(arr)
                artifact_meta[key] = meta.as_dict()
                optional_meta_present[key] = meta.as_dict()
            else:
                optional_meta_absent[key] = "not-defined"

        # Save optional fields manifest matching error-and-optional-fields-v1
        optional_manifest = {
            "schema": "error-and-optional-fields-v1",
            "frozen_fields": {k: artifact_meta[k] for k in FROZEN_TENSOR_KEYS},
            "optional_fields_present": optional_meta_present,
            "optional_fields_absent": optional_meta_absent,
            "provenance": self.provenance.as_dict(),
        }
        write_json(artifacts_dir / "optional_fields_manifest.json", optional_manifest)

        return UnifiedInferenceResult(
            run_id=rid,
            run_dir=bundle_dir,
            input_tensor=arr_input,
            base_tensor=arr_base,
            proposal_tensor=arr_prop,
            candidate_tensor=arr_cand,
            final_tensor=arr_final,
            target_tensor=target_tensor,
            optional_tensors=opts,
            metrics=computed_metrics,
            provenance=self.provenance,
            artifact_metadata=artifact_meta,
        )
